[theme]
primaryColor = "#1E3A5F"
backgroundColor = "#F8F5F7"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#2A3242"
font = "sans serif"

[client]
toolbarMode = "auto"
showSidebarNavigation = false

[browser]
gatherUsageStats = false
